# Generated by Django 4.1.7 on 2023-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('peace', 'peace'), ('litre', 'litre'), ('pack', 'pack'), ('bottle', 'bottle')], default='Kg', max_length=50),
        ),
    ]
