# Generated by Django 4.1.7 on 2023-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_country_order_country_name_alter_address_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='district_name',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='state_name',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
