# Generated by Django 4.1.7 on 2023-04-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_country_district_name_country_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='country_name',
            new_name='country',
        ),
    ]
