# Generated by Django 4.1.7 on 2023-04-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_country_name_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='state_name',
        ),
    ]
