# Generated by Django 4.1.7 on 2023-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_name',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
