# Generated by Django 4.1.7 on 2023-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_country_country_name_country_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='country_name',
        ),
    ]
